defmodule Campfire.Uploads do
  @moduledoc """
  Stores uploaded files (avatars, the account logo, message attachments) on local disk.

  Files live in `config :campfire, :uploads_dir`. A key is a random string plus the original
  file's extension, e.g. `"Zm9vYmFyYmF6cXV4.png"`; store the key in the record's `*_key` column.
  """

  @doc "The uploads directory."
  def dir, do: Application.fetch_env!(:campfire, :uploads_dir)

  @doc "Copies the file at `source_path` into the store. `filename` only provides the extension."
  @spec store(Path.t(), String.t()) :: {:ok, String.t()} | {:error, term()}
  def store(source_path, filename) do
    key = new_key(filename)
    dest = path(key)

    with :ok <- File.mkdir_p(Path.dirname(dest)),
         {:ok, _bytes} <- File.copy(source_path, dest) do
      {:ok, key}
    end
  end

  @doc "Writes `binary` into the store. `filename` only provides the extension."
  @spec store_binary(binary(), String.t()) :: {:ok, String.t()} | {:error, term()}
  def store_binary(binary, filename) do
    key = new_key(filename)
    dest = path(key)

    with :ok <- File.mkdir_p(Path.dirname(dest)),
         :ok <- File.write(dest, binary) do
      {:ok, key}
    end
  end

  @doc "The absolute path of a stored file."
  @spec path(String.t()) :: Path.t()
  def path(key) when is_binary(key) do
    # Keys are generated by us, but never let one escape the uploads dir.
    Path.join(dir(), Path.basename(key))
  end

  @doc "Whether the file exists."
  def exists?(nil), do: false
  def exists?(key), do: File.regular?(path(key))

  @doc "Deletes a stored file. Missing files and nil keys are ignored."
  @spec delete(String.t() | nil) :: :ok
  def delete(nil), do: :ok

  def delete(key) do
    _ = File.rm(path(key))
    :ok
  end

  defp new_key(filename) do
    random = :crypto.strong_rand_bytes(18) |> Base.url_encode64(padding: false)
    random <> extension(filename)
  end

  defp extension(filename) do
    ext = filename |> to_string() |> Path.extname() |> String.downcase()
    if ext =~ ~r/\A\.[a-z0-9]{1,10}\z/, do: ext, else: ""
  end
end
