defmodule Campfire.Repo.Migrations.BoostRoomId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Added nullable first so existing boosts can be backfilled from their message's room.
    alter table(:boosts) do
      add :room_id,
          references(:rooms,
            column: :id,
            name: "boosts_room_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    execute """
            UPDATE boosts SET room_id = messages.room_id
            FROM messages WHERE boosts.message_id = messages.id
            """,
            ""

    alter table(:boosts) do
      modify :room_id, :bigint, null: false
    end
  end

  def down do
    drop constraint(:boosts, "boosts_room_id_fkey")

    alter table(:boosts) do
      remove :room_id
    end
  end
end
