defmodule Campfire.Repo.Migrations.AddAttachmentMetadataEmbedsAndCustomStyles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      add :custom_styles, :text
    end

    alter table(:messages) do
      add :attachment_width, :bigint
      add :attachment_height, :bigint
      add :attachment_thumbnail_key, :text
      add :embed, :map
    end
  end

  def down do
    alter table(:messages) do
      remove :embed
      remove :attachment_thumbnail_key
      remove :attachment_height
      remove :attachment_width
    end

    alter table(:accounts) do
      remove :custom_styles
    end
  end
end
