defmodule Campfire.Repo.Migrations.AddUserIdIndexesToSessionsAndBans do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:bans, [:user_id])

    create index(:sessions, [:user_id])
  end

  def down do
    drop_if_exists index(:sessions, [:user_id])

    drop_if_exists index(:bans, [:user_id])
  end
end
