defmodule Campfire.Repo.Migrations.CreateDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false, default: "Campfire"
      add :join_code, :text, null: false
      add :logo_key, :text
      add :restrict_room_creation_to_administrators, :boolean, null: false, default: false
      add :singleton_guard, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts, [:singleton_guard], name: "accounts_singleton_index")

    create table(:bans, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :ip_address, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :bigint, null: false
    end

    create index(:bans, [:ip_address])

    create table(:boosts, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :message_id, :bigint, null: false
      add :booster_id, :bigint, null: false
    end

    create index(:boosts, [:message_id])

    create table(:memberships, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :involvement, :text, null: false, default: "mentions"
      add :unread_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id, :bigint, null: false
      add :user_id, :bigint, null: false
    end

    create unique_index(:memberships, [:room_id, :user_id],
             name: "memberships_unique_room_user_index"
           )

    create index(:memberships, [:user_id])

    create table(:messages, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:boosts) do
      modify :message_id,
             references(:messages,
               column: :id,
               name: "boosts_message_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:messages) do
      add :body, :text, null: false, default: ""
      add :client_message_id, :text, null: false
      add :mentioned_user_ids, {:array, :bigint}, null: false, default: []
      add :attachment_key, :text
      add :attachment_filename, :text
      add :attachment_content_type, :text
      add :attachment_byte_size, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id, :bigint, null: false
      add :creator_id, :bigint, null: false
    end

    create index(:messages, [:room_id, :inserted_at, :id])

    create index(:messages, [:creator_id])

    create table(:rooms, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:memberships) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "memberships_room_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:messages) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "messages_room_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:rooms) do
      add :name, :text
      add :kind, :text, null: false
      add :direct_key, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :creator_id, :bigint, null: false
    end

    create unique_index(:rooms, [:direct_key], name: "rooms_unique_direct_key_index")

    create table(:searches, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :query, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :bigint, null: false
    end

    create unique_index(:searches, [:user_id, :query], name: "searches_unique_user_query_index")

    create table(:sessions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :token, :text, null: false
      add :ip_address, :text
      add :user_agent, :text
      add :last_active_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :bigint, null: false
    end

    create unique_index(:sessions, [:token], name: "sessions_unique_token_index")

    create table(:users, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:bans) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "bans_user_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:boosts) do
      modify :booster_id,
             references(:users,
               column: :id,
               name: "boosts_booster_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "memberships_user_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:messages) do
      modify :creator_id,
             references(:users,
               column: :id,
               name: "messages_creator_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("""
    ALTER TABLE messages ADD COLUMN search_vector tsvector
      GENERATED ALWAYS AS (
        to_tsvector(
          'english',
          coalesce(body, '') || ' ' ||
            regexp_replace(coalesce(attachment_filename, ''), '[^[:alnum:]]+', ' ', 'g')
        )
      ) STORED
    """)

    execute("""
    CREATE INDEX messages_search_vector_index ON messages USING GIN (search_vector)
    """)

    alter table(:rooms) do
      modify :creator_id,
             references(:users,
               column: :id,
               name: "rooms_creator_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nothing
             )
    end

    alter table(:searches) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "searches_user_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:sessions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "sessions_user_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:users) do
      add :name, :text, null: false
      add :email_address, :text
      add :password_hash, :text
      add :bio, :text
      add :role, :text, null: false, default: "member"
      add :status, :text, null: false, default: "active"
      add :bot_token, :text
      add :avatar_key, :text
      add :last_room_id, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:bot_token], name: "users_unique_bot_token_index")

    create unique_index(:users, [:email_address], name: "users_unique_email_index")

    create table(:webhooks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :url, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "webhooks_user_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:webhooks, [:user_id], name: "webhooks_unique_user_index")
  end

  def down do
    drop constraint(:webhooks, "webhooks_user_id_fkey")

    drop_if_exists unique_index(:webhooks, [:user_id], name: "webhooks_unique_user_index")

    drop table(:webhooks)

    drop_if_exists unique_index(:users, [:email_address], name: "users_unique_email_index")

    drop_if_exists unique_index(:users, [:bot_token], name: "users_unique_bot_token_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :last_room_id
      remove :avatar_key
      remove :bot_token
      remove :status
      remove :role
      remove :bio
      remove :password_hash
      remove :email_address
      remove :name
    end

    drop constraint(:sessions, "sessions_user_id_fkey")

    alter table(:sessions) do
      modify :user_id, :bigint
    end

    drop constraint(:searches, "searches_user_id_fkey")

    alter table(:searches) do
      modify :user_id, :bigint
    end

    drop constraint(:rooms, "rooms_creator_id_fkey")

    alter table(:rooms) do
      modify :creator_id, :bigint
    end

    execute("""
    DROP INDEX messages_search_vector_index
    """)

    execute("""
    ALTER TABLE messages DROP COLUMN search_vector
    """)

    drop constraint(:messages, "messages_creator_id_fkey")

    drop constraint(:messages, "messages_room_id_fkey")

    alter table(:messages) do
      modify :creator_id, :bigint
    end

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop constraint(:memberships, "memberships_room_id_fkey")

    alter table(:memberships) do
      modify :user_id, :bigint
    end

    drop constraint(:boosts, "boosts_booster_id_fkey")

    drop constraint(:boosts, "boosts_message_id_fkey")

    alter table(:boosts) do
      modify :booster_id, :bigint
    end

    drop constraint(:bans, "bans_user_id_fkey")

    alter table(:bans) do
      modify :user_id, :bigint
    end

    drop table(:users)

    drop_if_exists unique_index(:sessions, [:token], name: "sessions_unique_token_index")

    drop table(:sessions)

    drop_if_exists unique_index(:searches, [:user_id, :query],
                     name: "searches_unique_user_query_index"
                   )

    drop table(:searches)

    drop_if_exists unique_index(:rooms, [:direct_key], name: "rooms_unique_direct_key_index")

    alter table(:rooms) do
      remove :creator_id
      remove :updated_at
      remove :inserted_at
      remove :direct_key
      remove :kind
      remove :name
    end

    alter table(:messages) do
      modify :room_id, :bigint
    end

    alter table(:memberships) do
      modify :room_id, :bigint
    end

    drop table(:rooms)

    drop_if_exists index(:messages, [:creator_id])

    drop_if_exists index(:messages, [:room_id, :inserted_at, :id])

    alter table(:messages) do
      remove :creator_id
      remove :room_id
      remove :updated_at
      remove :inserted_at
      remove :attachment_byte_size
      remove :attachment_content_type
      remove :attachment_filename
      remove :attachment_key
      remove :mentioned_user_ids
      remove :client_message_id
      remove :body
    end

    alter table(:boosts) do
      modify :message_id, :bigint
    end

    drop table(:messages)

    drop_if_exists index(:memberships, [:user_id])

    drop_if_exists unique_index(:memberships, [:room_id, :user_id],
                     name: "memberships_unique_room_user_index"
                   )

    drop table(:memberships)

    drop_if_exists index(:boosts, [:message_id])

    drop table(:boosts)

    drop_if_exists index(:bans, [:ip_address])

    drop table(:bans)

    drop_if_exists unique_index(:accounts, [:singleton_guard], name: "accounts_singleton_index")

    drop table(:accounts)
  end
end
